# Site settings
title: zkwang
email: zkwang2014@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  This is blog for Kai. Go Gators!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zkwang.org" # the base hostname & protocol for your site
twitter_username: zkwang2014
github_username:  zkwang2014

# Build settings
markdown: kramdown

#Comments
comments : True
