# Site settings
title: zkwang
email: zkwang2014@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, my name is Kai. I'm currently a graduate student in U.S. Learning Git & jekyll.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zkwang.org" # the base hostname & protocol for your site
twitter_username: zkwang2014
github_username:  zkwang2014

# Build settings
markdown: kramdown
